sudo: false

language: php

env:
  - COMPOSER_DISABLE_XDEBUG_WARN=1

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - mv -f -v composer-travis-ci.json composer.json
  - composer self-update
  - travis_retry composer install --no-interaction

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false
